empty_message = '[class="js_cart_lines alert alert-info"]'
input_counter = '[class="js_quantity quantity form-control border-start-0 border-end-0"]'
product_price = '//*[@id="cart_products"]/div/div[3]/div[2]/span/span'
quantity_input = '//*[@id="cart_products"]/div/div[3]/div[1]/input'
product_counter = '//*[@id="o_main_nav"]/ul[2]/li[2]/a/div/sup'
discount_code = '[placeholder="Discount code..."]'
error_message = '[class="alert alert-danger text-start"]'
