add_to_cart_button = '#add_to_cart'
result_products = '.text-primary.text-decoration-none'
terms_and_condition_link = '[href="/terms"]'
cart_button = '//*[@id="o_main_nav"]//*[@href="/shop/cart"]'
product_title_on_cart_loc = '[class="d-inline align-top h6 fw-bold"]'
product_title_on_page_loc = '#product_details > h1'
product_counter = '//*[@id="o_main_nav"]/ul[2]/li[2]/a/div/sup'
currency_dropdown = '[class="dropdown-toggle btn btn-light"]'
currency_select_EUR = '[href="/shop/change_pricelist/3"]'
currency_price = '//*[@class="oe_price"]'
terms_headline = 'h1'
