search_field = '//*[@id="products_grid"]/div[1]/form/div/input'
result_products = '[class="text-primary text-decoration-none"]'
result_count = '//*[@id="products_grid"]/div[1]/form/div/button/span/small'
sort_dropdown = '//*[@id="products_grid"]/div[1]/div[2]/a/span[1]'
sort_by_name = '//*[@id="products_grid"]/div[1]/div[2]/div/a[3]/span'
field_min = '[class="multirange-min position-absolute opacity-75 opacity-100-hover mt-1"]'
field_max = '[class="multirange-max position-absolute opacity-75 opacity-100-hover mt-1 end-0"]'
input_min = '[class="form-control form-control-sm mb-2 mb-lg-1 multirange-min"]'
input_max = '[class="form-control form-control-sm mb-2 mb-lg-1 multirange-max"]'
product_price = '.oe_currency_value'
add_item_to_cart = '[class="btn btn-primary a-submit"]'
